import { Hotel, City, Character } from './models';

export const createDefaultHotel = (): Hotel => ({
  id: '',
  type: 'hotel',
  name: '',
  created: new Date().getMilliseconds(),
  modified: new Date().getMilliseconds(),
  address1: '',
  airportCode: '',
  amenityMask: 0,
  city: '',
  confidenceRating: 0,
  countryCode: '',
  deepLink: '',
  highRate: 0,
  hotelId: 0,
  hotelInDestination: false,
  hotelRating: 0,
  location: {
    latitude: 0,
    longitude: 0,
  },
  locationDescription: '',
  lowRate: 0,
  metadata: {
    path: '',
  },
  postalCode: 0,
  propertyCategory: 0,
  proximityDistance: 0,
  proximityUnit: '',
  rateCurrencyCode: '',
  shortDescription: '',
  stateProvinceCode: '',
  thumbNailUrl: '/thumbnails/50947_264_t.jpg',
  tripAdvisorRating: 0,
  tripAdvisorRatingUrl: '',
});

export const mockHotels: Hotel[] = [
  {
    id: '0248058a-27e4-11e6-ace6-a9876eff01b3',
    type: 'hotel',
    name: 'Motif Seattle',
    created: 1464777092568,
    modified: 1464777618676,
    address1: '1415 5th Ave',
    airportCode: 'SEA',
    amenityMask: 7798786,
    city: 'Seattle',
    confidenceRating: 52,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/125727/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 289,
    hotelId: 1257278,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.60985,
      longitude: -122.33475,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 259,
    metadata: {
      path: '/hotels/0248058a-27e4-11e6-ace6-a9876eff01b3',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.168453,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at Motif Seattle, you will be centrally located in Seattle, steps from 5th Avenue Theater and minutes from Pike Place Market. This 4-star hotel is within',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/50947_264_t.jpg',
    tripAdvisorRating: 3.5,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/3.5-12345-4.gif',
  },
  {
    id: '024bd61a-27e4-11e6-ad95-35ed01160e57',
    type: 'hotel',
    name: 'The Westin Seattle',
    created: 1464777092593,
    modified: 1464871217352,
    address1: '1900 5th Ave',
    airportCode: 'SEA',
    amenityMask: 7806977,
    city: 'Seattle',
    confidenceRating: 5,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/164122/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 259,
    hotelId: 164122,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.61309,
      longitude: -122.33788,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 209,
    metadata: {
      path: '/hotels/024bd61a-27e4-11e6-ad95-35ed01160e57',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.335604,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      "With a stay at The Westin Seattle, you'll be centrally laocated in Seattle, steps from Westlake Center and minutes from Pacific Place. This 4-star hotel is close to",
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/16673_260_t.jpg',
    tripAdvisorRating: 4,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '024fcdba-27e4-11e6-af44-cd4c8e537e9c',
    type: 'hotel',
    name: 'Sheraton Seattle Hotel',
    created: 1464777092619,
    modified: 1464777092619,
    address1: '1400 6th Ave',
    airportCode: 'SEA',
    amenityMask: 262147,
    city: 'Seattle',
    confidenceRating: 30,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/164116/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 320,
    hotelId: 164116,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.61017,
      longitude: -122.33357,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 205,
    metadata: {
      path: '/hotels/024fcdba-27e4-11e6-af44-cd4c8e537e9c',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.115907,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      "With a stay at Sheraton Seattle Hotel, you'll be centrally located in Seattle, steps from 5th Avenue Theater and Washington State Convention Center. This 4-star",
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/25290_88_t.jpg',
    tripAdvisorRating: 4,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '0253773a-27e4-11e6-8ffe-278d3b0d044c',
    type: 'hotel',
    name: 'The Edgewater - A Noble House Hotel',
    created: 1464777092643,
    modified: 1464777092643,
    address1: 'Pier 67, 2411 Alaskan Way',
    airportCode: 'SEA',
    amenityMask: 5701635,
    city: 'Burlingame',
    confidenceRating: 95,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/127092/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 269,
    hotelId: 127092,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.61252,
      longitude: -122.35013,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 179,
    metadata: {
      path: '/hotels/0253773a-27e4-11e6-8ffe-278d3b0d044c',
    },
    postalCode: 98121,
    propertyCategory: 1,
    proximityDistance: 11.898841,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      "With a stay at The Edgewater - A Noble House Hotel, you'll be centrally located in Seattle, steps from Bell Street Cruise Terminal at Pier 66 and minutes from",
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/11133_169_t.jpg',
    tripAdvisorRating: 4,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '025720ba-27e4-11e6-8744-efc6f2251051',
    type: 'hotel',
    name: 'Hotel Max, a Provenance Hotel',
    created: 1464777092667,
    modified: 1464777092667,
    address1: '620 Stewart St',
    airportCode: 'SEA',
    amenityMask: 3,
    city: 'Burlingame',
    confidenceRating: 52,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/113426/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 188.202,
    hotelId: 113426,
    hotelInDestination: true,
    hotelRating: 3,
    location: {
      latitude: 47.61381,
      longitude: -122.33686,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 187.202,
    metadata: {
      path: '/hotels/025720ba-27e4-11e6-8744-efc6f2251051',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.293709,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at Hotel Max, a Provenance Hotel in Seattle (Belltown), you&apos;ll be minutes from Westlake Center and Washington State Convention Center. This hotel is',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/28647_30_t.jpg',
    tripAdvisorRating: 4,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '025b3f6a-27e4-11e6-80d7-1ba3f907ab71',
    type: 'hotel',
    name: 'Hotel Monaco Seattle, a Kimpton Hotel',
    created: 1464777092694,
    modified: 1464777092694,
    address1: '1101 4th Ave',
    airportCode: 'SEA',
    amenityMask: 1310720,
    city: 'Seattle',
    confidenceRating: 52,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/132138/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 489,
    hotelId: 132138,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.60682,
      longitude: -122.33358,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 189,
    metadata: {
      path: '/hotels/025b3f6a-27e4-11e6-80d7-1ba3f907ab71',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.097676,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at Hotel Monaco Seattle, a Kimpton Hotel, you&apos;ll be centrally located in Seattle, steps from Seattle Public Library and Safeco Headquarters. This 4-star',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/62800_122_t.jpg',
    tripAdvisorRating: 4.5,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-12345-4.gif',
  },
  {
    id: '025f5e1a-27e4-11e6-a36c-9fede5552112',
    type: 'hotel',
    name: 'Hotel Deca - A Noble House Hotel',
    created: 1464777092721,
    modified: 1464777092721,
    address1: '4507 Brooklyn Avenue NE',
    airportCode: 'SEA',
    amenityMask: 3,
    city: 'Burlingame',
    confidenceRating: 95,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/191964/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 159,
    hotelId: 191964,
    hotelInDestination: true,
    hotelRating: 3,
    location: {
      latitude: 47.66143,
      longitude: -122.31429,
    },
    locationDescription: 'In Seattle (University District)',
    lowRate: 119,
    metadata: {
      path: '/hotels/025f5e1a-27e4-11e6-a36c-9fede5552112',
    },
    postalCode: 98105,
    propertyCategory: 1,
    proximityDistance: 11.145046,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at Hotel Deca - A Noble House Hotel in Seattle (University District), you&apos;ll be minutes from Burke Museum of Natural History and Culture and close to',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/19023_103_t.jpg',
    tripAdvisorRating: 4,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '026355c4-27e4-11e6-b3f9-09f86925339f',
    type: 'hotel',
    name: 'W Seattle',
    created: 1464777092747,
    modified: 1464777092747,
    address1: '1112 4th Ave',
    airportCode: 'SEA',
    amenityMask: 7798785,
    city: 'Seattle',
    confidenceRating: 5,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/213497/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 210,
    hotelId: 213497,
    hotelInDestination: true,
    hotelRating: 5,
    location: {
      latitude: 47.60688,
      longitude: -122.33361,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 175,
    metadata: {
      path: '/hotels/026355c4-27e4-11e6-b3f9-09f86925339f',
    },
    postalCode: 98101,
    propertyCategory: 1,
    proximityDistance: 11.09939,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at W Seattle, you&apos;ll be centrally located in Seattle, steps from Seattle Public Library and Safeco Headquarters. This 4-star hotel is close to Pike Place',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/284304_50_t.jpg',
    tripAdvisorRating: 5,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif',
  },
  {
    id: '0267c28a-27e4-11e6-ab3b-5f1a4c39ef62',
    type: 'hotel',
    name: 'Hotel Andra',
    created: 1464777092776,
    modified: 1464777092776,
    address1: '2000 4th Ave',
    airportCode: 'SEA',
    amenityMask: 1441795,
    city: 'Seattle',
    confidenceRating: 45,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/119562/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 239.5368,
    hotelId: 119562,
    hotelInDestination: true,
    hotelRating: 4,
    location: {
      latitude: 47.61318,
      longitude: -122.34009,
    },
    locationDescription: 'Near Pike Place Market',
    lowRate: 189.4252,
    metadata: {
      path: '/hotels/0267c28a-27e4-11e6-ab3b-5f1a4c39ef62',
    },
    postalCode: 98121,
    propertyCategory: 1,
    proximityDistance: 11.438348,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at Hotel Andra, you&apos;ll be centrally located in Seattle, minutes from Westlake Center and Pike Place Market. This 4-star hotel is within close proximity',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/16950_158_t.jpg',
    tripAdvisorRating: 4.5,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-12345-4.gif',
  },
  {
    id: '026ccbae-27e4-11e6-afa7-536abd83599c',
    type: 'hotel',
    name: 'The Maxwell Hotel - Pineapple Hospitality',
    created: 1464777092809,
    modified: 1464777092809,
    address1: '300 Roy St',
    airportCode: 'SEA',
    amenityMask: 7798786,
    city: 'Seattle',
    confidenceRating: 95,
    countryCode: 'US',
    deepLink:
      'http://www.travelnow.com/templates/55505/hotels/342070/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null',
    highRate: 289,
    hotelId: 342070,
    hotelInDestination: true,
    hotelRating: 3,
    location: {
      latitude: 47.62561,
      longitude: -122.35129,
    },
    locationDescription: 'Near Pacific Northwest Ballet',
    lowRate: 229,
    metadata: {
      path: '/hotels/026ccbae-27e4-11e6-afa7-536abd83599c',
    },
    postalCode: 98109,
    propertyCategory: 1,
    proximityDistance: 12.074359,
    proximityUnit: 'MI',
    rateCurrencyCode: 'USD',
    shortDescription:
      'With a stay at The Maxwell Hotel - Pineapple Hospitality, you&apos;ll be centrally located in Seattle, steps from Pacific Northwest Ballet and Teatro ZinZanni. This',
    stateProvinceCode: 'WA',
    thumbNailUrl: '/thumbnails/3445681_43_t.jpg',
    tripAdvisorRating: 4.5,
    tripAdvisorRatingUrl:
      'http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-12345-4.gif',
  },
];

export const mockCities: City[] = [
  {
    id: 'Seattle',
    name: 'Seattle',
  },
  {
    id: 'Chicago',
    name: 'Chicago',
  },
  {
    id: 'New York',
    name: 'New York',
  },
  {
    id: 'California',
    name: 'California',
  },
  {
    id: 'Burlingame',
    name: 'Burlingame',
  },
];

export const mockCharacters: Character[] = [
  {
    id: 1,
    name: 'Rick Sanchez',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/3',
      'https://rickandmortyapi.com/api/episode/4',
      'https://rickandmortyapi.com/api/episode/5',
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/12',
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/14',
      'https://rickandmortyapi.com/api/episode/15',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/17',
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/20',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/23',
      'https://rickandmortyapi.com/api/episode/24',
      'https://rickandmortyapi.com/api/episode/25',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/27',
      'https://rickandmortyapi.com/api/episode/28',
      'https://rickandmortyapi.com/api/episode/29',
      'https://rickandmortyapi.com/api/episode/30',
      'https://rickandmortyapi.com/api/episode/31',
      'https://rickandmortyapi.com/api/episode/32',
      'https://rickandmortyapi.com/api/episode/33',
      'https://rickandmortyapi.com/api/episode/34',
      'https://rickandmortyapi.com/api/episode/35',
      'https://rickandmortyapi.com/api/episode/36',
      'https://rickandmortyapi.com/api/episode/37',
      'https://rickandmortyapi.com/api/episode/38',
      'https://rickandmortyapi.com/api/episode/39',
      'https://rickandmortyapi.com/api/episode/40',
      'https://rickandmortyapi.com/api/episode/41',
      'https://rickandmortyapi.com/api/episode/42',
      'https://rickandmortyapi.com/api/episode/43',
      'https://rickandmortyapi.com/api/episode/44',
      'https://rickandmortyapi.com/api/episode/45',
      'https://rickandmortyapi.com/api/episode/46',
      'https://rickandmortyapi.com/api/episode/47',
      'https://rickandmortyapi.com/api/episode/48',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/50',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/1',
    created: '2017-11-04T18:48:46.250Z',
  },
  {
    id: 2,
    name: 'Morty Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/3',
      'https://rickandmortyapi.com/api/episode/4',
      'https://rickandmortyapi.com/api/episode/5',
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/12',
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/14',
      'https://rickandmortyapi.com/api/episode/15',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/17',
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/20',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/23',
      'https://rickandmortyapi.com/api/episode/24',
      'https://rickandmortyapi.com/api/episode/25',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/27',
      'https://rickandmortyapi.com/api/episode/28',
      'https://rickandmortyapi.com/api/episode/29',
      'https://rickandmortyapi.com/api/episode/30',
      'https://rickandmortyapi.com/api/episode/31',
      'https://rickandmortyapi.com/api/episode/32',
      'https://rickandmortyapi.com/api/episode/33',
      'https://rickandmortyapi.com/api/episode/34',
      'https://rickandmortyapi.com/api/episode/35',
      'https://rickandmortyapi.com/api/episode/36',
      'https://rickandmortyapi.com/api/episode/37',
      'https://rickandmortyapi.com/api/episode/38',
      'https://rickandmortyapi.com/api/episode/39',
      'https://rickandmortyapi.com/api/episode/40',
      'https://rickandmortyapi.com/api/episode/41',
      'https://rickandmortyapi.com/api/episode/42',
      'https://rickandmortyapi.com/api/episode/43',
      'https://rickandmortyapi.com/api/episode/44',
      'https://rickandmortyapi.com/api/episode/45',
      'https://rickandmortyapi.com/api/episode/46',
      'https://rickandmortyapi.com/api/episode/47',
      'https://rickandmortyapi.com/api/episode/48',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/50',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/2',
    created: '2017-11-04T18:50:21.651Z',
  },
  {
    id: 3,
    name: 'Summer Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/12',
      'https://rickandmortyapi.com/api/episode/14',
      'https://rickandmortyapi.com/api/episode/15',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/17',
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/20',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/23',
      'https://rickandmortyapi.com/api/episode/24',
      'https://rickandmortyapi.com/api/episode/25',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/27',
      'https://rickandmortyapi.com/api/episode/29',
      'https://rickandmortyapi.com/api/episode/30',
      'https://rickandmortyapi.com/api/episode/31',
      'https://rickandmortyapi.com/api/episode/32',
      'https://rickandmortyapi.com/api/episode/33',
      'https://rickandmortyapi.com/api/episode/34',
      'https://rickandmortyapi.com/api/episode/35',
      'https://rickandmortyapi.com/api/episode/36',
      'https://rickandmortyapi.com/api/episode/38',
      'https://rickandmortyapi.com/api/episode/39',
      'https://rickandmortyapi.com/api/episode/40',
      'https://rickandmortyapi.com/api/episode/41',
      'https://rickandmortyapi.com/api/episode/42',
      'https://rickandmortyapi.com/api/episode/43',
      'https://rickandmortyapi.com/api/episode/44',
      'https://rickandmortyapi.com/api/episode/45',
      'https://rickandmortyapi.com/api/episode/46',
      'https://rickandmortyapi.com/api/episode/47',
      'https://rickandmortyapi.com/api/episode/48',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/3',
    created: '2017-11-04T19:09:56.428Z',
  },
  {
    id: 4,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/12',
      'https://rickandmortyapi.com/api/episode/14',
      'https://rickandmortyapi.com/api/episode/15',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/20',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/23',
      'https://rickandmortyapi.com/api/episode/24',
      'https://rickandmortyapi.com/api/episode/25',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/27',
      'https://rickandmortyapi.com/api/episode/28',
      'https://rickandmortyapi.com/api/episode/29',
      'https://rickandmortyapi.com/api/episode/30',
      'https://rickandmortyapi.com/api/episode/31',
      'https://rickandmortyapi.com/api/episode/32',
      'https://rickandmortyapi.com/api/episode/33',
      'https://rickandmortyapi.com/api/episode/34',
      'https://rickandmortyapi.com/api/episode/35',
      'https://rickandmortyapi.com/api/episode/36',
      'https://rickandmortyapi.com/api/episode/38',
      'https://rickandmortyapi.com/api/episode/39',
      'https://rickandmortyapi.com/api/episode/40',
      'https://rickandmortyapi.com/api/episode/41',
      'https://rickandmortyapi.com/api/episode/42',
      'https://rickandmortyapi.com/api/episode/43',
      'https://rickandmortyapi.com/api/episode/44',
      'https://rickandmortyapi.com/api/episode/45',
      'https://rickandmortyapi.com/api/episode/46',
      'https://rickandmortyapi.com/api/episode/47',
      'https://rickandmortyapi.com/api/episode/48',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/4',
    created: '2017-11-04T19:22:43.665Z',
  },
  {
    id: 5,
    name: 'Jerry Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/7',
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/9',
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/12',
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/14',
      'https://rickandmortyapi.com/api/episode/15',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/20',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/23',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/29',
      'https://rickandmortyapi.com/api/episode/30',
      'https://rickandmortyapi.com/api/episode/31',
      'https://rickandmortyapi.com/api/episode/32',
      'https://rickandmortyapi.com/api/episode/33',
      'https://rickandmortyapi.com/api/episode/35',
      'https://rickandmortyapi.com/api/episode/36',
      'https://rickandmortyapi.com/api/episode/38',
      'https://rickandmortyapi.com/api/episode/39',
      'https://rickandmortyapi.com/api/episode/40',
      'https://rickandmortyapi.com/api/episode/41',
      'https://rickandmortyapi.com/api/episode/42',
      'https://rickandmortyapi.com/api/episode/43',
      'https://rickandmortyapi.com/api/episode/44',
      'https://rickandmortyapi.com/api/episode/45',
      'https://rickandmortyapi.com/api/episode/46',
      'https://rickandmortyapi.com/api/episode/47',
      'https://rickandmortyapi.com/api/episode/48',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/50',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/5',
    created: '2017-11-04T19:26:56.301Z',
  },
  {
    id: 6,
    name: 'Abadango Cluster Princess',
    status: 'Alive',
    species: 'Alien',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Abadango',
      url: 'https://rickandmortyapi.com/api/location/2',
    },
    location: {
      name: 'Abadango',
      url: 'https://rickandmortyapi.com/api/location/2',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/27'],
    url: 'https://rickandmortyapi.com/api/character/6',
    created: '2017-11-04T19:50:28.250Z',
  },
  {
    id: 7,
    name: 'Abradolf Lincler',
    status: 'unknown',
    species: 'Human',
    type: 'Genetic experiment',
    gender: 'Male',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: {
      name: 'Testicle Monster Dimension',
      url: 'https://rickandmortyapi.com/api/location/21',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/11',
    ],
    url: 'https://rickandmortyapi.com/api/character/7',
    created: '2017-11-04T19:59:20.523Z',
  },
  {
    id: 8,
    name: 'Adjudicator Rick',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/28'],
    url: 'https://rickandmortyapi.com/api/character/8',
    created: '2017-11-04T20:03:34.737Z',
  },
  {
    id: 9,
    name: 'Agency Director',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/24'],
    url: 'https://rickandmortyapi.com/api/character/9',
    created: '2017-11-04T20:06:54.976Z',
  },
  {
    id: 10,
    name: 'Alan Rails',
    status: 'Dead',
    species: 'Human',
    type: 'Superhuman (Ghost trains summoner)',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: "Worldender's lair",
      url: 'https://rickandmortyapi.com/api/location/4',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/25'],
    url: 'https://rickandmortyapi.com/api/character/10',
    created: '2017-11-04T20:19:09.017Z',
  },
  {
    id: 11,
    name: 'Albert Einstein',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/12'],
    url: 'https://rickandmortyapi.com/api/character/11',
    created: '2017-11-04T20:20:20.965Z',
  },
  {
    id: 12,
    name: 'Alexander',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Anatomy Park',
      url: 'https://rickandmortyapi.com/api/location/5',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/3'],
    url: 'https://rickandmortyapi.com/api/character/12',
    created: '2017-11-04T20:32:33.144Z',
  },
  {
    id: 13,
    name: 'Alien Googah',
    status: 'unknown',
    species: 'Alien',
    type: '',
    gender: 'unknown',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/31'],
    url: 'https://rickandmortyapi.com/api/character/13',
    created: '2017-11-04T20:33:30.779Z',
  },
  {
    id: 14,
    name: 'Alien Morty',
    status: 'unknown',
    species: 'Alien',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
    url: 'https://rickandmortyapi.com/api/character/14',
    created: '2017-11-04T20:51:31.373Z',
  },
  {
    id: 15,
    name: 'Alien Rick',
    status: 'unknown',
    species: 'Alien',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
    url: 'https://rickandmortyapi.com/api/character/15',
    created: '2017-11-04T20:56:13.215Z',
  },
  {
    id: 16,
    name: 'Amish Cyborg',
    status: 'Dead',
    species: 'Alien',
    type: 'Parasite',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/15'],
    url: 'https://rickandmortyapi.com/api/character/16',
    created: '2017-11-04T21:12:45.235Z',
  },
  {
    id: 17,
    name: 'Annie',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Anatomy Park',
      url: 'https://rickandmortyapi.com/api/location/5',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/3'],
    url: 'https://rickandmortyapi.com/api/character/17',
    created: '2017-11-04T22:21:24.481Z',
  },
  {
    id: 18,
    name: 'Antenna Morty',
    status: 'Alive',
    species: 'Human',
    type: 'Human with antennae',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/28',
    ],
    url: 'https://rickandmortyapi.com/api/character/18',
    created: '2017-11-04T22:25:29.008Z',
  },
  {
    id: 19,
    name: 'Antenna Rick',
    status: 'unknown',
    species: 'Human',
    type: 'Human with antennae',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: { name: 'unknown', url: '' },
    image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
    url: 'https://rickandmortyapi.com/api/character/19',
    created: '2017-11-04T22:28:13.756Z',
  },
  {
    id: 20,
    name: 'Ants in my Eyes Johnson',
    status: 'unknown',
    species: 'Human',
    type: 'Human with ants in his eyes',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/8'],
    url: 'https://rickandmortyapi.com/api/character/20',
    created: '2017-11-04T22:34:53.659Z',
  },
  {
    id: 21,
    name: 'Aqua Morty',
    status: 'unknown',
    species: 'Humanoid',
    type: 'Fish-Person',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/21.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/22',
    ],
    url: 'https://rickandmortyapi.com/api/character/21',
    created: '2017-11-04T22:39:48.055Z',
  },
  {
    id: 22,
    name: 'Aqua Rick',
    status: 'unknown',
    species: 'Humanoid',
    type: 'Fish-Person',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/22.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/28',
    ],
    url: 'https://rickandmortyapi.com/api/character/22',
    created: '2017-11-04T22:41:07.171Z',
  },
  {
    id: 23,
    name: 'Arcade Alien',
    status: 'unknown',
    species: 'Alien',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Immortality Field Resort',
      url: 'https://rickandmortyapi.com/api/location/7',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/23.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/25',
      'https://rickandmortyapi.com/api/episode/26',
    ],
    url: 'https://rickandmortyapi.com/api/character/23',
    created: '2017-11-05T08:43:05.095Z',
  },
  {
    id: 24,
    name: 'Armagheadon',
    status: 'Alive',
    species: 'Alien',
    type: 'Cromulon',
    gender: 'Male',
    origin: {
      name: 'Signus 5 Expanse',
      url: 'https://rickandmortyapi.com/api/location/22',
    },
    location: {
      name: 'Signus 5 Expanse',
      url: 'https://rickandmortyapi.com/api/location/22',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/24.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/16'],
    url: 'https://rickandmortyapi.com/api/character/24',
    created: '2017-11-05T08:48:30.776Z',
  },
  {
    id: 25,
    name: 'Armothy',
    status: 'Dead',
    species: 'unknown',
    type: 'Self-aware arm',
    gender: 'Male',
    origin: {
      name: 'Post-Apocalyptic Earth',
      url: 'https://rickandmortyapi.com/api/location/8',
    },
    location: {
      name: 'Post-Apocalyptic Earth',
      url: 'https://rickandmortyapi.com/api/location/8',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/25.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/23'],
    url: 'https://rickandmortyapi.com/api/character/25',
    created: '2017-11-05T08:54:29.343Z',
  },
  {
    id: 26,
    name: 'Arthricia',
    status: 'Alive',
    species: 'Alien',
    type: 'Cat-Person',
    gender: 'Female',
    origin: {
      name: 'Purge Planet',
      url: 'https://rickandmortyapi.com/api/location/9',
    },
    location: {
      name: 'Purge Planet',
      url: 'https://rickandmortyapi.com/api/location/9',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/26.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/20'],
    url: 'https://rickandmortyapi.com/api/character/26',
    created: '2017-11-05T08:56:46.165Z',
  },
  {
    id: 27,
    name: 'Artist Morty',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/27.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/10',
      'https://rickandmortyapi.com/api/episode/28',
    ],
    url: 'https://rickandmortyapi.com/api/character/27',
    created: '2017-11-05T08:59:07.457Z',
  },
  {
    id: 28,
    name: 'Attila Starwar',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/28.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/17',
    ],
    url: 'https://rickandmortyapi.com/api/character/28',
    created: '2017-11-05T09:02:16.595Z',
  },
  {
    id: 29,
    name: 'Baby Legs',
    status: 'Alive',
    species: 'Human',
    type: 'Human with baby legs',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/29.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/8'],
    url: 'https://rickandmortyapi.com/api/character/29',
    created: '2017-11-05T09:06:19.644Z',
  },
  {
    id: 30,
    name: 'Baby Poopybutthole',
    status: 'Alive',
    species: 'Poopybutthole',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: { name: 'unknown', url: '' },
    image: 'https://rickandmortyapi.com/api/character/avatar/30.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/31'],
    url: 'https://rickandmortyapi.com/api/character/30',
    created: '2017-11-05T09:13:16.483Z',
  },
  {
    id: 31,
    name: 'Baby Wizard',
    status: 'Dead',
    species: 'Alien',
    type: 'Parasite',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/31.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/15'],
    url: 'https://rickandmortyapi.com/api/character/31',
    created: '2017-11-05T09:15:11.286Z',
  },
  {
    id: 32,
    name: 'Bearded Lady',
    status: 'Dead',
    species: 'Alien',
    type: 'Parasite',
    gender: 'Female',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/32.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/15'],
    url: 'https://rickandmortyapi.com/api/character/32',
    created: '2017-11-05T09:18:04.184Z',
  },
  {
    id: 33,
    name: 'Beebo',
    status: 'Dead',
    species: 'Alien',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Venzenulon 7',
      url: 'https://rickandmortyapi.com/api/location/10',
    },
    location: {
      name: 'Venzenulon 7',
      url: 'https://rickandmortyapi.com/api/location/10',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/33.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/29'],
    url: 'https://rickandmortyapi.com/api/character/33',
    created: '2017-11-05T09:21:55.595Z',
  },
  {
    id: 34,
    name: 'Benjamin',
    status: 'Alive',
    species: 'Poopybutthole',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/34.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/8',
      'https://rickandmortyapi.com/api/episode/13',
      'https://rickandmortyapi.com/api/episode/17',
    ],
    url: 'https://rickandmortyapi.com/api/character/34',
    created: '2017-11-05T09:24:04.748Z',
  },
  {
    id: 35,
    name: 'Bepisian',
    status: 'Alive',
    species: 'Alien',
    type: 'Bepisian',
    gender: 'unknown',
    origin: {
      name: 'Bepis 9',
      url: 'https://rickandmortyapi.com/api/location/11',
    },
    location: {
      name: 'Bepis 9',
      url: 'https://rickandmortyapi.com/api/location/11',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/35.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/19',
      'https://rickandmortyapi.com/api/episode/25',
    ],
    url: 'https://rickandmortyapi.com/api/character/35',
    created: '2017-11-05T09:27:38.491Z',
  },
  {
    id: 36,
    name: 'Beta-Seven',
    status: 'Alive',
    species: 'Alien',
    type: 'Hivemind',
    gender: 'unknown',
    origin: { name: 'unknown', url: '' },
    location: { name: 'unknown', url: '' },
    image: 'https://rickandmortyapi.com/api/character/avatar/36.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/14'],
    url: 'https://rickandmortyapi.com/api/character/36',
    created: '2017-11-05T09:31:08.952Z',
  },
  {
    id: 37,
    name: 'Beth Sanchez',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Earth (C-500A)',
      url: 'https://rickandmortyapi.com/api/location/23',
    },
    location: {
      name: 'Earth (C-500A)',
      url: 'https://rickandmortyapi.com/api/location/23',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/37.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/8'],
    url: 'https://rickandmortyapi.com/api/character/37',
    created: '2017-11-05T09:38:22.960Z',
  },
  {
    id: 38,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/38.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/1',
      'https://rickandmortyapi.com/api/episode/2',
      'https://rickandmortyapi.com/api/episode/3',
      'https://rickandmortyapi.com/api/episode/4',
      'https://rickandmortyapi.com/api/episode/5',
      'https://rickandmortyapi.com/api/episode/6',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/38',
    created: '2017-11-05T09:48:44.230Z',
  },
  {
    id: 39,
    name: 'Beth Smith',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Female',
    origin: {
      name: "Earth (Evil Rick's Target Dimension)",
      url: 'https://rickandmortyapi.com/api/location/34',
    },
    location: {
      name: "Earth (Evil Rick's Target Dimension)",
      url: 'https://rickandmortyapi.com/api/location/34',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/39.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
    url: 'https://rickandmortyapi.com/api/character/39',
    created: '2017-11-05T09:52:31.777Z',
  },
  {
    id: 40,
    name: "Beth's Mytholog",
    status: 'Dead',
    species: 'Mythological Creature',
    type: 'Mytholog',
    gender: 'Female',
    origin: {
      name: 'Nuptia 4',
      url: 'https://rickandmortyapi.com/api/location/13',
    },
    location: {
      name: 'Nuptia 4',
      url: 'https://rickandmortyapi.com/api/location/13',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/40.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/18'],
    url: 'https://rickandmortyapi.com/api/character/40',
    created: '2017-11-05T10:02:26.701Z',
  },
  {
    id: 41,
    name: 'Big Boobed Waitress',
    status: 'Alive',
    species: 'Mythological Creature',
    type: '',
    gender: 'Female',
    origin: {
      name: 'Fantasy World',
      url: 'https://rickandmortyapi.com/api/location/48',
    },
    location: {
      name: 'Fantasy World',
      url: 'https://rickandmortyapi.com/api/location/48',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/41.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/5'],
    url: 'https://rickandmortyapi.com/api/character/41',
    created: '2017-11-05T10:13:45.960Z',
  },
  {
    id: 42,
    name: 'Big Head Morty',
    status: 'unknown',
    species: 'Human',
    type: 'Human with giant head',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/42.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/22'],
    url: 'https://rickandmortyapi.com/api/character/42',
    created: '2017-11-05T10:15:53.349Z',
  },
  {
    id: 43,
    name: 'Big Morty',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/43.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/28'],
    url: 'https://rickandmortyapi.com/api/character/43',
    created: '2017-11-05T10:17:04.997Z',
  },
  {
    id: 44,
    name: 'Body Guard Morty',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/44.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/28'],
    url: 'https://rickandmortyapi.com/api/character/44',
    created: '2017-11-05T10:18:11.062Z',
  },
  {
    id: 45,
    name: 'Bill',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    location: {
      name: 'Earth (C-137)',
      url: 'https://rickandmortyapi.com/api/location/1',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/45.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/3'],
    url: 'https://rickandmortyapi.com/api/character/45',
    created: '2017-11-05T10:22:27.446Z',
  },
  {
    id: 46,
    name: 'Bill',
    status: 'unknown',
    species: 'Animal',
    type: 'Dog',
    gender: 'Male',
    origin: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    location: { name: 'unknown', url: '' },
    image: 'https://rickandmortyapi.com/api/character/avatar/46.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/2'],
    url: 'https://rickandmortyapi.com/api/character/46',
    created: '2017-11-05T10:24:38.089Z',
  },
  {
    id: 47,
    name: 'Birdperson',
    status: 'Alive',
    species: 'Alien',
    type: 'Bird-Person',
    gender: 'Male',
    origin: {
      name: 'Bird World',
      url: 'https://rickandmortyapi.com/api/location/15',
    },
    location: {
      name: 'Planet Squanch',
      url: 'https://rickandmortyapi.com/api/location/35',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/47.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/11',
      'https://rickandmortyapi.com/api/episode/16',
      'https://rickandmortyapi.com/api/episode/21',
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/26',
      'https://rickandmortyapi.com/api/episode/49',
      'https://rickandmortyapi.com/api/episode/51',
    ],
    url: 'https://rickandmortyapi.com/api/character/47',
    created: '2017-11-05T11:13:36.018Z',
  },
  {
    id: 48,
    name: 'Black Rick',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/48.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/22',
      'https://rickandmortyapi.com/api/episode/28',
    ],
    url: 'https://rickandmortyapi.com/api/character/48',
    created: '2017-11-05T11:15:26.044Z',
  },
  {
    id: 49,
    name: 'Blamph',
    status: 'Alive',
    species: 'Alien',
    type: '',
    gender: 'unknown',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/49.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/19'],
    url: 'https://rickandmortyapi.com/api/character/49',
    created: '2017-11-05T11:18:26.702Z',
  },
  {
    id: 50,
    name: 'Blim Blam',
    status: 'Alive',
    species: 'Alien',
    type: 'Korblock',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Earth (Replacement Dimension)',
      url: 'https://rickandmortyapi.com/api/location/20',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/50.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/14'],
    url: 'https://rickandmortyapi.com/api/character/50',
    created: '2017-11-05T11:21:43.756Z',
  },
  {
    id: 51,
    name: 'Blue Diplomat',
    status: 'Alive',
    species: 'Alien',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/51.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/19'],
    url: 'https://rickandmortyapi.com/api/character/51',
    created: '2017-11-05T11:24:49.688Z',
  },
  {
    id: 52,
    name: 'Blue Footprint Guy',
    status: 'Dead',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: {
      name: 'Post-Apocalyptic Earth',
      url: 'https://rickandmortyapi.com/api/location/8',
    },
    location: {
      name: 'Post-Apocalyptic Earth',
      url: 'https://rickandmortyapi.com/api/location/8',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/52.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/23'],
    url: 'https://rickandmortyapi.com/api/character/52',
    created: '2017-11-05T11:26:42.084Z',
  },
  {
    id: 53,
    name: 'Blue Shirt Morty',
    status: 'unknown',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Citadel of Ricks',
      url: 'https://rickandmortyapi.com/api/location/3',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/53.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/10'],
    url: 'https://rickandmortyapi.com/api/character/53',
    created: '2017-11-05T11:28:38.627Z',
  },
  {
    id: 54,
    name: 'Bobby Moynihan',
    status: 'Alive',
    species: 'Human',
    type: '',
    gender: 'Male',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Interdimensional Cable',
      url: 'https://rickandmortyapi.com/api/location/6',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/54.jpeg',
    episode: ['https://rickandmortyapi.com/api/episode/8'],
    url: 'https://rickandmortyapi.com/api/character/54',
    created: '2017-11-05T11:31:26.348Z',
  },
  {
    id: 55,
    name: 'Boobloosian',
    status: 'Dead',
    species: 'Alien',
    type: 'Boobloosian',
    gender: 'unknown',
    origin: { name: 'unknown', url: '' },
    location: {
      name: 'Nuptia 4',
      url: 'https://rickandmortyapi.com/api/location/13',
    },
    image: 'https://rickandmortyapi.com/api/character/avatar/55.jpeg',
    episode: [
      'https://rickandmortyapi.com/api/episode/18',
      'https://rickandmortyapi.com/api/episode/21',
    ],
    url: 'https://rickandmortyapi.com/api/character/55',
    created: '2017-11-05T11:32:53.847Z',
  },
];
